# Generated by Django 5.1.7 on 2025-03-30 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collegeName', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=15)),
                ('collegeCode', models.IntegerField()),
            ],
        ),
    ]
